### ISSUE TITLE
Weapon gets overwritten when picking a new one up (Picking up a pistol when you already have a rifle)

### ISSUE THREAD

**Issue by Ascaped** [VerseferaStudios/DevilsPunishment#6]

**Comment by christoph2005** [comment]
working on it

**Comment by christoph2005** [comment]
This behavior was deemed desireable (left-4-dead).
However the issue at hand here may have been fixed when fixing https://github.com/VerseferaStudios/DevilsPunishment/issues/5

So I guess this bug is "closed"
